FROM golang:1.11.5-stretch

ARG UID
ARG GID

RUN groupadd -f  -g ${GID} developer && \
    useradd  -d /go -u ${UID} -g ${GID} developer && \
    chown -R developer /go

ENV GO111MODULE=on
WORKDIR /go/src/github.com/jlevesy/go-sind

USER $UID
