FROM golang:1.12-stretch

ARG UID
ARG GID

RUN groupadd -f  -g ${GID} developer && \
    useradd  -d /go -u ${UID} -g ${GID} developer && \
    curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.13.1 && \
    chown -R developer /go

ENV GO111MODULE=on
WORKDIR /go/src/github.com/jlevesy/go-sind

USER $UID
