#!/bin/sh

CURRENT_DIR="$(cd "$(dirname "${0}")" && pwd -P)"

docker run \
    -ti \
     --rm \
    -v "${CURRENT_DIR}:/go/src/github.com/jlevesy/go-sind" \
    -v "${CURRENT_DIR}/.gocache/mod:/go/pkg/mod" \
    -v "${CURRENT_DIR}/.gocache/build:/go/.cache/go-build" \
    go-sind-toolbox \
    "${*:-bash}"
